# Site
name: "Akash's Blog"
title: "Blog"
description: "Hello there! Welcome to my blog. I write stuff - notes, how-to-do-s, hobbies and more."
logo: 'assets/images/akash.svg'
favicon: 'assets/images/nerd_glasses.png'
# The blog index.html is server from akash-116.github.io/blog/site
baseurl: "/blog"
# Where the static site is generated {no significance in frontend, this is for building}
# destination: '' 
# google_analytics: 'UA-xxxxxxxx-1'
disqus: 'akash-116-blog'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: akash.gillella@gmail.com

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    avatar: 'assets/images/avatar-sal.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/donate/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Memoirs, a Bootstrap Medium styled template available for Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Write a short description of the author here. You are currently previewing Memoirs demo, a Jekyll template compatible with Github pages."
  akash:
    name: Akash Reddy Gillella
    display_name: Akash    
    avatar: 'assets/images/avatar.png'
    email: akash.gillella@gmail.com
    web: https://akash-116.github.io/
    twitter: https://twitter.com/akash_gillella
    description: "Akash is currently a final year undergraduate at IIT, Bombay. He is majoring in Computer Science. He likes to write about tech guides to various stuff he deems interesting"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
